### ISSUE TITLE
DatePicker fallback selects wrong date if client and server timezone differs

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/touchkit#273]
**Originally by @mstahv**

---

DatePicker fallback selects wrong date if client and server timezone differs

---

 Imported from https://dev.vaadin.com/ issue #12783

**Comment by JuanCalderon** [comment]
And the solutions is...?

**Comment by mstahv** [comment]
I think it should be fairly easy to fix this on the server side as Vaadin already detects the client timezone. I'm though quite certain that Vaadin will fix this here, unless you have an active pro subscirption with Bugfix Priority. So I'd raise an issue to the open source fork of this and try to fix it there (or at least create a new issue there):

https://github.com/parttio/touchkit

**Comment by xylo** [comment]
Thanks, Matti.  Since https://github.com/parttio/touchkit became the main repository for touchkit, I wonder how new issues can be opened there.  I didn't find any button for that.

**Comment by mstahv** [comment]
Ah, yep. Needed to enable the issues in project settings as it is a "fork" of this repository. Now enabled: https://github.com/parttio/touchkit/issues

**Comment by xylo** [comment]
Thanks, Matti.
