### ISSUE TITLE
Problems with touchkit 4.1 with chrome and firefox.

### ISSUE THREAD

**Issue by tullio0106** [vaadin/touchkit#435]
I've some problems with the touchkit 4.1 and Vaadin 7.7.26.
Using chrome (latest version 91.0) it simply doesn't work : white page:
Using firefox 89.0.2 it exibits a wery strange behaviour if I run it using localhost it works if I run using an ip addres again white page.
From the same server, if I use MSIE 11 it works perfectly also using an ip in the url.
Using very old chrome versions again it works.
Tks

**Comment by TatuLund** [comment]
Fixed in version 4.2.1

**Comment by tullio0106** [comment]
I tried to download the 4.2.1 version but I wasnt' able to find it.

My maven is

            &lt;groupId&gt;com.vaadin.addon&lt;/groupId&gt;

            &lt;artifactId&gt;vaadin-touchkit-cval&lt;/artifactId&gt;

            &lt;version&gt;4.2.1&lt;/version&gt;



Tks

**Comment by TatuLund** [comment]
Can you try now again. Something had gone wrong with saving action.

https://vaadin.com/directory/component/vaadin-touchkit

**Comment by tullio0106** [comment]
Unfortunately I downloaded 4.2.1 but nothing changed.
Firefox still work only from localhost, Chrome doesn't work at all.
Firefox consolle reports, when fails :
`Uncaught TypeError: $wnd.applicationCache is undefined
    awc http://192.168.1.94:8080/oc/touchlight line 9 > injectedScript:70
    cwc http://192.168.1.94:8080/oc/touchlight line 9 > injectedScript:134
    mTb http://192.168.1.94:8080/oc/touchlight line 9 > injectedScript:141
    g http://192.168.1.94:8080/oc/touchlight line 9 > injectedScript:106
    wB http://192.168.1.94:8080/oc/touchlight line 9 > injectedScript:302
    zB http://192.168.1.94:8080/oc/touchlight line 9 > injectedScript:10
    yB http://192.168.1.94:8080/oc/touchlight line 9 > injectedScript:21
    jTb http://192.168.1.94:8080/oc/touchlight line 9 > injectedScript:107
    <anonymous> TouchLightWidgetSet-0.js:1
    m http://192.168.1.94:8080/oc/VAADIN/widgetsets/TouchLightWidgetSet/TouchLightWidgetSet.nocache.js:9
    onScriptDownloaded http://192.168.1.94:8080/oc/VAADIN/widgetsets/TouchLightWidgetSet/TouchLightWidgetSet.nocache.js:10
    d http://192.168.1.94:8080/oc/VAADIN/widgetsets/TouchLightWidgetSet/TouchLightWidgetSet.nocache.js:6
    e http://192.168.1.94:8080/oc/VAADIN/widgetsets/TouchLightWidgetSet/TouchLightWidgetSet.nocache.js:7
    setInterval handler*l http://192.168.1.94:8080/oc/VAADIN/widgetsets/TouchLightWidgetSet/TouchLightWidgetSet.nocache.js:7
    onScriptDownloaded http://192.168.1.94:8080/oc/VAADIN/widgetsets/TouchLightWidgetSet/TouchLightWidgetSet.nocache.js:10
    <anonymous> http://192.168.1.94:8080/oc/VAADIN/widgetsets/TouchLightWidgetSet/3EE9F760E752D2DD8551F4CB91331E05.cache.js:1
touchlight line 9 > injectedScript:70:17
`
Chrome console reports :
`TouchLightWidgetSet-0.js:7912 Uncaught TypeError: Cannot read property 'addEventListener' of undefined
    at awc (TouchLightWidgetSet-0.js:7912)
    at cwc (TouchLightWidgetSet-0.js:7158)
    at Array.mTb (TouchLightWidgetSet-0.js:6795)
    at g (TouchLightWidgetSet-0.js:6954)
    at wB (TouchLightWidgetSet-0.js:3457)
    at zB (TouchLightWidgetSet-0.js:7034)
    at eval (TouchLightWidgetSet-0.js:6458)
    at jTb (TouchLightWidgetSet-0.js:6955)
    at eval (TouchLightWidgetSet-0.js:8196)
    at <anonymous>:1:1`
Hope this help
Tks

**Comment by tullio0106** [comment]
I'm still waiting for a definitive answer for my problem .
The problem is still open.
Tks
